DATA_DIR = r"C:\project_data\commute_hack"

# DATA_DIR = r"C:\dev\data\commute_hack"

SHORTEN_NAMES = {
    "net profit / total assets": "net_profit_pct",
    "total liabilities / total assets": "total_liabilities_pct",
    "working capital / total assets": "working_capital_pct",
    "current assets / short-term liabilities": "assests_to_liabilities",
    "[(cash + short-term securities + receivables - short-term liabilities) / (operating expenses - depreciation)] * 365": "annual_cash_per_expenses",
    "retained earnings / total assets": "retained_earnings_pct",
    "EBIT / total assets": "ebit_pct",
    "book value of equity / total liabilities": "equity_per_total_liabils",
    "sales / total assets": "sales_pct",
    "equity / total assets": "equity_pct",
    "(gross profit + extraordinary items + financial expenses) / total assets": "gross_ext_profit_pct",
    "gross profit / short-term liabilities": "gross_profit_to_total_liabils",
    "(gross profit + depreciation) / sales": "profit_depre_to_sales",
    "(gross profit + interest) / total assets": "gross_profit_int_pct",
    "(total liabilities * 365) / (gross profit + depreciation)": "annual_total_liabils_profit_depre",
    "(gross profit + depreciation) / total liabilities": "profit_depre_to_total_liabils",
    "total assets / total liabilities": "assets_per_total_liabils",
    "gross profit / total assets": "gross_profit_pct",
    "gross profit / sales": "gross_profit_to_sales",
    "(inventory * 365) / sales": "annual_inventoryto_sales",
    "sales (n) / sales (n-1)": "previous_day_sales_pct",
    "profit on operating activities / total assets": "activity_profit_pct",
    "net profit / sales": "net_profit_to_sales",
    "gross profit (in 3 years) / total assets": "gross_3yr_porfit_pct",
    "(equity - share capital) / total assets": "equity_minus_shares_pct",
    "(net profit + depreciation) / total liabilities": "net_profit_deprec_per_total_liabils",
    "profit on operating activities / financial expenses": "operating_profit_per_expenses",
    "working capital / fixed assets": "working_captial_to_fixed_assets",
    "logarithm of total assets": "total_assets_log",
    "(total liabilities - cash) / sales": "liabilites_to_sales",
    "(gross profit + interest) / sales": "gross_profit_int_to_sales",
    "(current liabilities * 365) / cost of products sold": "annual_liabil_to_cost",
    "operating expenses / short-term liabilities": "opr_exp_per_liabilities",
    "operating expenses / total liabilities": "opr_exp_per_total_liabils",
    "profit on sales / total assets": "sales_profit_pct",
    "total sales / total assets": "total_sales_pct",
    "(current assets - inventories) / long-term liabilities": "assets_to_total_liabils",
    "constant capital / total assets": "constant_capital_pct",
    "profit on sales / sales": "profit_per_sales",
    "(current assets - inventory - receivables) / short-term liabilities": "assests_less_inv_rec_liabilities",
    "total liabilities / ((profit on operating activities + depreciation) * (12/365))": "mnthly_total_liabils_per_oper_profit",
    "profit on operating activities / sales": "oper_profit_to_sales",
    "rotation receivables + inventory turnover in days": "daily_rec_int_turnover",
    "(receivables * 365) / sales": "rec_to_sales",
    "net profit / inventory": "net_profit_to_invent",
    "(current assets - inventory) / short-term liabilities": "assests_less_inv_to_liabilities",
    "(inventory * 365) / cost of products sold": "annual_inventory_per_costs",
    "EBITDA (profit on operating activities - depreciation) / total assets": "ebita_pct",
    "EBITDA (profit on operating activities - depreciation) / sales": "ebita_to_sales",
    "current assets / total liabilities": "current_assets_per_total_liabils",
    "short-term liabilities / total assets": "liabilities_pct",
    "(short-term liabilities * 365) / cost of products sold)": "liabilities_per_costs",
    "equity / fixed assets": "equity_to_fixed_assets",
    "constant capital / fixed assets": "capital_to_fixed_assets",
    "working capital": "working_capital",
    "(sales - cost of products sold) / sales": "profit_to_sales",
    "(current assets - inventory - short-term liabilities) / (sales - gross profit - depreciation)": "assets_to_costs",
    "total costs /total sales": "costs_to_sales",
    "long-term liabilities / equity": "liabilites_per_equity",
    "sales / inventory": "sales_to_inventory",
    "sales / receivables": "sales_to_receivables",
    "(short-term liabilities *365) / sales": "annual_liabilities_to_sales",
    "sales / short-term liabilities": "sales_to_liabilities",
    "sales / fixed assets": "sales_to_fixed_assets",
    "bankruptcy_label": "bankruptcy_label",
}
